### ISSUE TITLE
Bitte Aktualisierung wireguard-ui auf Version 0.4.0 durchführen

### ISSUE THREAD

**Issue by Siggi0904** [KleSecGmbH/ioBroker#7]
Hallo,

könnte das Installationsscript für wireguard-ui bitte auf Version 0.4.0 aktualisiert werden?

Siehe: https://github.com/ngoduykhanh/wireguard-ui

Vielen Dank im Voraus.

**Comment by KleSecGmbH** [comment]
Behoben durch Pull Request #8
